version: '3.1'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.21
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    volumes:
      - /zero/docker-compose/log/nginx:/var/log/nginx
      - /zero/docker-compose/config/nginx:/etc/nginx/conf.d
      - /zero/docker-compose/data/zero-blog/html:/usr/share/nginx/html
    networks:
      - zero
networks:
  zero:
    external: true
